##### Travis setup for the package ####
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
# Workaround for testing Python 3.7:
# https://github.com/travis-ci/travis-ci/issues/9815
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: yes

before_install:
  - pip install --upgrade setuptools pip
  - pip install --upgrade pylint pytest pytest-pylint pytest-runner

install:
  - pip install -r requirements.txt

script: 
  - python -m pytest      # Run the tests without IPython.

# install: source build_tools/travis/install.sh
# after_success: source build_tools/travis/after_success.sh



